terminate called after throwing an instance of 'std::bad_alloc'
terminate called after throwing an instance of '  what():  std::bad_allocSt9bad_alloc'

  what():  St9bad_alloc
<Feb 24 18:13:06.584506> BE_MPI (ERROR): The error message in the job record is as follows:
<Feb 24 18:13:06.584572> BE_MPI (ERROR):   "killed with signal 6"
