terminate called after throwing an instance of 'std::bad_alloc'
  what():  St9bad_alloc
terminate called after throwing an instance of 'std::bad_alloc'
  what():  St9bad_alloc
<Feb 24 18:11:29.503149> BE_MPI (ERROR): The error message in the job record is as follows:
<Feb 24 18:11:29.503227> BE_MPI (ERROR):   "killed with signal 6"
